version: '3'

services:
  wisteria:
    container_name: wisteria
    build: ./
    ports:
        - 8090:8080
        - 8091:8081
    privileged: true
    volumes:
        - ./app:/app
    tty: true
    stdin_open: true
    networks:
        - laradock_frontend
networks:
    laradock_frontend:
      external: true
